### ISSUE TITLE
idle connection details

### ISSUE THREAD

**Issue by agrath** [ronascentes/sql-tools#1]
If you are using sp_who2 you can get sleeping connections however sp_who3 only returns active/running connections.
Being able to filter by database is valuable but that is not available with sp_who2 (and we need to see the last query)
Is it possible to include idle connections, perhaps with a parameter?

**Comment by ronascentes** [comment]
Yes, just need to add 2 clauses below and query only to sys.dm_exec_session. I'm planning to add it. Many thanks for asking.
```
WHERE EXISTS (SELECT * FROM sys.dm_tran_session_transactions AS t WHERE t.session_id = s.session_id) 
AND NOT EXISTS (SELECT * FROM sys.dm_exec_requests AS r WHERE r.session_id = s.session_id)
```

**Comment by naveenrpendli** [comment]
While I was testing the SP_WHO3 2, the result set doesn't display the database name for the sql_text that it was doing the activity.

![image](https://user-images.githubusercontent.com/25126027/29781422-29d79f80-8be7-11e7-9016-7dd941afca38.png)

**Comment by ronascentes** [comment]
Hi @agrath just to let you know that I'm working a new version to include idle and sleeping connections details. Thank you for looging this issue.

**Comment by ronascentes** [comment]
@naveenrpendli I'm working a new version of SP_WHO3 so that issue will be addressed. Thanks.

**Comment by ronascentes** [comment]
Fixed. New version of sp_who3 is available.
